### PR TITLE
Update server.py, client.py

### PR DESCRIPTION
**Pull request by Someone8859**
[server.py] UPDATED:
Using functions
Automatically re-listen when there is broken pipe
We can now close session (shutdown the server - server.py, not the whole machine!!) with an "exit" command.

[client.py] UPDATED:
Using functions
When you just pressing "enter" with nothing (inp <= 0), the command will not be sent so it won't freeze both the server and client.
Handle for broken pipe (just a bit)

### CODE REVIEW

**Comment by Oggy250413** [comment]
Wow!

**Review by Oggy250413 — APPROVED** [review]
OK! Commit

**Comment by Someone8859** [comment]
Have you checked the code carefully?

**Comment by Oggy250413** [comment]
Yes.

**Comment by Oggy250413** [comment]
I will modify it a bit after when you merge.

**Pull request merged**
